ETAPS_VISITAS_PADRAO = [
    {"etap_id": 1, "etap_descricao": "AGENDAMENTO", "etap_cor": '#19c37d'   },
    {"etap_id": 2, "etap_descricao": "CONTATO INICIAL", "etap_cor": '#f0ad4e'}, 
    {"etap_id": 3, "etap_descricao": "INVESTIGAÇÃO", "etap_cor": '#6c5ce7'},
    {"etap_id": 4, "etap_descricao": "LEAD", "etap_cor": '#9b59b6'},
    {"etap_id": 5, "etap_descricao": "NEGOCACAO", "etap_cor": '#5b8def'},
    {"etap_id": 6, "etap_descricao": "ORÇAMENTOS GANHOS", "etap_cor": '#19c37d'},
    {"etap_id": 7, "etap_descricao": "ORCAMENTOS PERDIDOS", "etap_cor": '#ff6b6b'},
    {"etap_id": 8, "etap_descricao": "POS VENDA - OCORRÊNCIAS GERAIS", "etap_cor": '#20c997'},
    {"etap_id": 9, "etap_descricao": "PROSPECÇÃO", "etap_cor": '#22b7d8'},  
    {"etap_id": 10, "etap_descricao": "PRE-ORÇAMENTOS", "etap_cor": '#ffc107'},
    {"etap_id": 11, "etap_descricao": "PEDIDOS ANTIGOS PESQUISA", "etap_cor": '#ff7eb6'},
    {"etap_id": 12, "etap_descricao": "POSATORE OCORRÊNCIAS EM OBRAS.", "etap_cor": '#f0ad4e'},
    {"etap_id": 13, "etap_descricao": "RT - RESERVA TÉCNICA.", "etap_cor": '#ffc107'},
    {"etap_id": 14, "etap_descricao": "SAIDAS PARTICULARES", "etap_cor": '#8d6e63'},
    {"etap_id": 15, "etap_descricao": "VISITA EXTERNA", "etap_cor": '#22b7d8'},
    {"etap_id": 16, "etap_descricao": "VISITA CLIENTE LOJA", "etap_cor": '#7f8c8d'},
    {"etap_id": 17, "etap_descricao": "ETAPA INICIAL DE CONTATOS", "etap_cor": '#5b8def'},
    {"etap_id": 18, "etap_descricao": "FLUXO GANHO", "etap_cor": '#19c37d'},
    {"etap_id": 19, "etap_descricao": "PERDA", "etap_cor": '#ff6b6b'},
    {"etap_id": 20, "etap_descricao": "FOLLOW UP", "etap_cor": '#a8b4c2'},
    {"etap_id": 21, "etap_descricao": "ABERTO", "etap_cor": '#5cb85c'},
    {"etap_id": 22, "etap_descricao": "CANCELADO", "etap_cor": '#5cb85c'},
    {"etap_id": 23, "etap_descricao": "EXPORTADO PEDIDO", "etap_cor": '#5cb85c'},
]

