# Generated by Django 2.2.28 on 2026-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosPisosArquivos',
            fields=[
                ('arqu_empr', models.IntegerField(primary_key=True, serialize=False)),
                ('arqu_pedi', models.IntegerField(unique=True)),
                ('arqu_arqu', models.BinaryField(blank=True, null=True)),
                ('arqu_nome_arqu', models.CharField(blank=True, max_length=100, null=True)),
                ('arqu_cod_arqu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedidospisosarquivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusPisos',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('stat_empr', models.IntegerField()),
                ('stat_fili', models.IntegerField()),
                ('stat_codigo', models.IntegerField()),
                ('stat_desc', models.CharField(max_length=40)),
                ('stat_tipo', models.IntegerField(choices=[(0, 'ORCAMENTO'), (1, 'PEDIDO')], default=0)),
                ('stat_ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'status_pisos',
                'ordering': ['stat_tipo', 'stat_codigo'],
                'unique_together': {('stat_empr', 'stat_fili', 'stat_tipo', 'stat_codigo')},
            },
        ),
    ]
