# Generated by Django 2.2.28 on 2026-05-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pisos', '0002_pedidospisosarquivos_statuspisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspisos',
            name='stat_cor',
            field=models.CharField(default='#6c757d', max_length=20),
        ),
    ]
