# Generated by Django 2.2.28 on 2026-05-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_empr', models.IntegerField()),
                ('mark_fili', models.IntegerField()),
                ('mark_prod_codi', models.CharField(max_length=60)),
                ('mark_sku_codi', models.CharField(max_length=60)),
                ('mark_marketplace', models.CharField(default='mercado_livre', max_length=30)),
                ('mark_stat', models.CharField(choices=[('PENDENTE', 'Pendente'), ('INTEGRANDO', 'Integrando'), ('INTEGRADO', 'Integrado'), ('ERRO', 'Erro'), ('PAUSADO', 'Pausado')], default='PENDENTE', max_length=20)),
                ('mark_sync_preco', models.BooleanField(default=True)),
                ('mark_sync_esto', models.BooleanField(default=True)),
                ('mark_ulti_erro', models.TextField(blank=True, null=True)),
                ('mark_criado_em', models.DateTimeField(auto_now_add=True)),
                ('mark_atua_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketplace_produto',
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceproduto',
            index=models.Index(fields=['mark_empr', 'mark_fili'], name='marketplace_mark_em_436970_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceproduto',
            index=models.Index(fields=['mark_prod_codi'], name='marketplace_mark_pr_62f0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceproduto',
            index=models.Index(fields=['mark_stat'], name='marketplace_mark_st_2aec3f_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceproduto',
            index=models.Index(fields=['mark_marketplace'], name='marketplace_mark_ma_7f0536_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketplaceproduto',
            unique_together={('mark_empr', 'mark_fili', 'mark_prod_codi', 'mark_marketplace')},
        ),
    ]
