# Generated by Django 2.2.28 on 2026-05-20 09:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceAnuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maan_item_id', models.CharField(blank=True, max_length=60, null=True)),
                ('maan_titu', models.CharField(max_length=255)),
                ('maan_cate_id', models.CharField(blank=True, max_length=60, null=True)),
                ('maan_tipo_anun', models.CharField(default='gold_special', max_length=30)),
                ('maan_prec', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('maan_esto', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('maan_stat', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado'), ('ERRO', 'Erro')], default='RASCUNHO', max_length=20)),
                ('maan_url', models.CharField(blank=True, max_length=255, null=True)),
                ('maan_payload_env', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('maan_payload_ret', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('maan_cria_em', models.DateTimeField(auto_now_add=True)),
                ('maan_atua_em', models.DateTimeField(auto_now=True)),
                ('maan_produto', models.ForeignKey(db_column='maan_produto_id', on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='marketplace.MarketplaceProduto')),
            ],
            options={
                'db_table': 'marketplace_anuncio',
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceanuncio',
            index=models.Index(fields=['maan_item_id'], name='marketplace_maan_it_3c8294_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceanuncio',
            index=models.Index(fields=['maan_stat'], name='marketplace_maan_st_862928_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceanuncio',
            index=models.Index(fields=['maan_produto'], name='marketplace_maan_pr_06675f_idx'),
        ),
    ]
