# Generated by Django 2.2.28 on 2026-01-14 16:20
# Versão idempotente: só renomeia se a coluna 'total' existir e 'total_item' não existir.

from django.db import migrations


def _rename_total_seguro(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return

    with connection.cursor() as cursor:
        # Verifica se a tabela existe
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
              AND table_name = 'nf_nota_item'
            """
        )
        if not cursor.fetchone():
            # Tabela não existe ainda (ex: 0001 foi 'fakeada' indevidamente).
            # Não falha aqui; a ausência da tabela é tratada fora desta migration.
            return

        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'nf_nota_item'
              AND column_name IN ('total', 'total_item')
            """
        )
        cols = {r[0] for r in cursor.fetchall()}

    if "total" in cols and "total_item" not in cols:
        schema_editor.execute(
            'ALTER TABLE nf_nota_item RENAME COLUMN "total" TO "total_item"'
        )
    # Se 'total_item' já existe, a renomeação já foi feita: não faz nada.


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('Notas_Fiscais', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_rename_total_seguro, _noop_reverse),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='notaitem',
                    old_name='total',
                    new_name='total_item',
                ),
            ],
        ),
    ]
