# Generated by Django 2.2.28 on 2026-06-10 12:23

from django.db import migrations, models
import django.db.models.deletion


def _executar_sql_seguro(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return

    statements = [
        """
        ALTER TABLE IF EXISTS nf_nota
            ADD COLUMN IF NOT EXISTS icms_uf_dest_valor_total NUMERIC(15,2) NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS informacoes_adicionais TEXT NULL,
            ADD COLUMN IF NOT EXISTS valor_total_tributos NUMERIC(15,2) NULL DEFAULT 0;
        """,
        """
        ALTER TABLE IF EXISTS nf_nota_item
            ADD COLUMN IF NOT EXISTS informacoes_adicionais TEXT NULL,
            ADD COLUMN IF NOT EXISTS numero_item_pedido INTEGER NULL,
            ADD COLUMN IF NOT EXISTS numero_pedido VARCHAR(20) NULL,
            ADD COLUMN IF NOT EXISTS valor_total_tributos NUMERIC(15,2) NULL DEFAULT 0;
        """,
        """
        ALTER TABLE IF EXISTS nf_item_imposto
            ADD COLUMN IF NOT EXISTS icms_uf_dest_aliquota NUMERIC(5,2) NULL,
            ADD COLUMN IF NOT EXISTS icms_uf_dest_base NUMERIC(15,2) NULL,
            ADD COLUMN IF NOT EXISTS icms_uf_dest_fcp_valor NUMERIC(15,2) NULL,
            ADD COLUMN IF NOT EXISTS icms_uf_dest_partilha NUMERIC(5,2) NULL,
            ADD COLUMN IF NOT EXISTS icms_uf_dest_valor NUMERIC(15,2) NULL;
        """,
        """
        CREATE TABLE IF NOT EXISTS nf_nota_fatura (
            id serial PRIMARY KEY,
            numero VARCHAR(60) NULL,
            valor_original NUMERIC(15,2) NULL,
            valor_desconto NUMERIC(15,2) NULL,
            valor_liquido NUMERIC(15,2) NULL,
            nota_id INTEGER NOT NULL
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS nf_nota_duplicata (
            id serial PRIMARY KEY,
            ordem INTEGER NOT NULL DEFAULT 1,
            numero VARCHAR(60) NOT NULL,
            data_vencimento DATE NULL,
            valor NUMERIC(15,2) NULL,
            fatura_id INTEGER NULL,
            nota_id INTEGER NOT NULL
        );
        """,
        "CREATE INDEX IF NOT EXISTS nf_nota_item_numero_pedido_idx ON nf_nota_item (numero_pedido);",
        "CREATE UNIQUE INDEX IF NOT EXISTS nf_nota_fat_nota_uk ON nf_nota_fatura (nota_id);",
        "CREATE INDEX IF NOT EXISTS nf_nota_fat_nota_id_d5c72f_idx ON nf_nota_fatura (nota_id);",
        "CREATE INDEX IF NOT EXISTS nf_nota_dup_nota_id_35fe7b_idx ON nf_nota_duplicata (nota_id);",
        "CREATE INDEX IF NOT EXISTS nf_nota_dup_fatura__c3f1cd_idx ON nf_nota_duplicata (fatura_id);",
        "CREATE UNIQUE INDEX IF NOT EXISTS nf_nota_dup_nota_numero_uk ON nf_nota_duplicata (nota_id, numero);",
    ]

    try:
        with connection.cursor() as cursor:
            for statement in statements:
                try:
                    cursor.execute(statement)
                except Exception:
                    continue
    except Exception:
        return


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('Notas_Fiscais', '0006_nota_item_beneficio_ibscbs'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _executar_sql_seguro,
                    _noop_reverse,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='nota',
                    name='icms_uf_dest_valor_total',
                    field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
                ),
                migrations.AddField(
                    model_name='nota',
                    name='informacoes_adicionais',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='nota',
                    name='valor_total_tributos',
                    field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
                ),
                migrations.AddField(
                    model_name='notaitem',
                    name='informacoes_adicionais',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='notaitem',
                    name='numero_item_pedido',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='notaitem',
                    name='numero_pedido',
                    field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
                ),
                migrations.AddField(
                    model_name='notaitem',
                    name='valor_total_tributos',
                    field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
                ),
                migrations.AddField(
                    model_name='notaitemimposto',
                    name='icms_uf_dest_aliquota',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                migrations.AddField(
                    model_name='notaitemimposto',
                    name='icms_uf_dest_base',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                migrations.AddField(
                    model_name='notaitemimposto',
                    name='icms_uf_dest_fcp_valor',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                migrations.AddField(
                    model_name='notaitemimposto',
                    name='icms_uf_dest_partilha',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                migrations.AddField(
                    model_name='notaitemimposto',
                    name='icms_uf_dest_valor',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
                ),
                migrations.CreateModel(
                    name='NotaFatura',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('numero', models.CharField(blank=True, max_length=60, null=True)),
                        ('valor_original', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                        ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                        ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                        ('nota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fatura', to='Notas_Fiscais.Nota')),
                    ],
                    options={
                        'verbose_name': 'Fatura da Nota Fiscal',
                        'verbose_name_plural': 'Faturas das Notas Fiscais',
                        'db_table': 'nf_nota_fatura',
                    },
                ),
                migrations.CreateModel(
                    name='NotaDuplicata',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('ordem', models.PositiveIntegerField(default=1)),
                        ('numero', models.CharField(max_length=60)),
                        ('data_vencimento', models.DateField(blank=True, null=True)),
                        ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                        ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicatas', to='Notas_Fiscais.NotaFatura')),
                        ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicatas', to='Notas_Fiscais.Nota')),
                    ],
                    options={
                        'verbose_name': 'Duplicata da Nota Fiscal',
                        'verbose_name_plural': 'Duplicatas das Notas Fiscais',
                        'db_table': 'nf_nota_duplicata',
                    },
                ),
                migrations.AddIndex(
                    model_name='notafatura',
                    index=models.Index(fields=['nota'], name='nf_nota_fat_nota_id_d5c72f_idx'),
                ),
                migrations.AddIndex(
                    model_name='notaduplicata',
                    index=models.Index(fields=['nota'], name='nf_nota_dup_nota_id_35fe7b_idx'),
                ),
                migrations.AddIndex(
                    model_name='notaduplicata',
                    index=models.Index(fields=['fatura'], name='nf_nota_dup_fatura__c3f1cd_idx'),
                ),
                migrations.AlterUniqueTogether(
                    name='notaduplicata',
                    unique_together={('nota', 'numero')},
                ),
            ],
        ),
    ]
