# Generated by Django 2.2.28 on 2026-04-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_empr', models.IntegerField()),
                ('proc_fili', models.IntegerField()),
                ('proc_desc', models.CharField(max_length=255)),
                ('proc_stat', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_VALIDACAO', 'Em validação'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('proc_data_aber', models.DateTimeField(auto_now_add=True)),
                ('proc_data_fech', models.DateTimeField(blank=True, null=True)),
                ('proc_usro_aber', models.IntegerField(blank=True, null=True)),
                ('proc_usro_vali', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'processo',
            },
        ),
        migrations.CreateModel(
            name='ChecklistModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chmo_empr', models.IntegerField()),
                ('chmo_fili', models.IntegerField()),
                ('chmo_nome', models.CharField(max_length=120)),
                ('chmo_ativ', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'checklist_modelo',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chit_empr', models.IntegerField()),
                ('chit_fili', models.IntegerField()),
                ('chit_desc', models.CharField(max_length=255)),
                ('chit_obri', models.BooleanField(default=True)),
                ('chit_mode', models.ForeignKey(db_column='chit_mode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='itens', to='processos.ChecklistModelo')),
            ],
            options={
                'db_table': 'checklist_item',
            },
        ),
        migrations.CreateModel(
            name='ProcessoChecklistResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pchr_empr', models.IntegerField()),
                ('pchr_fili', models.IntegerField()),
                ('pchr_resp', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não se aplica')], max_length=3, null=True)),
                ('pchr_obse', models.TextField(blank=True, null=True)),
                ('pchr_vali', models.BooleanField(default=False)),
                ('pchr_data_vali', models.DateTimeField(blank=True, null=True)),
                ('pchr_usro_vali', models.IntegerField(blank=True, null=True)),
                ('pchr_item', models.ForeignKey(db_column='pchr_item', on_delete=django.db.models.deletion.DO_NOTHING, to='processos.ChecklistItem')),
                ('pchr_proc', models.ForeignKey(db_column='pchr_proc', on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='processos.Processo')),
            ],
            options={
                'db_table': 'processo_checklist_resposta',
                'unique_together': {('pchr_proc', 'pchr_item')},
            },
        ),
    ]
