# Generated by Django 2.2.28 on 2026-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='proc_clie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='processo',
            name='proc_os',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='proc_os_cria_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
