# Generated by Django 2.2.28 on 2026-08-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20260513_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='proc_enti_vali',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='proc_mode',
            field=models.ForeignKey(db_column='proc_mode', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='processos.ChecklistModelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processochecklistresposta',
            name='pchr_enti_vali',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='proc_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='proc_os',
            field=models.ForeignKey(blank=True, db_column='proc_os', null=True, on_delete=django.db.models.deletion.SET_NULL, to='O_S.Os'),
        ),
    ]
