# Generated by Django 2.2.28 on 2026-08-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_auto_20260824_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processochecklistresposta',
            name='pchr_item',
            field=models.ForeignKey(db_column='pchr_item', on_delete=django.db.models.deletion.CASCADE, to='processos.ChecklistItem'),
        ),
    ]
