# Generated by Django 2.2.28 on 2026-08-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_auto_20260824_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='processochecklistresposta',
            name='pchr_obri',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processochecklistresposta',
            name='pchr_item',
            field=models.ForeignKey(db_column='pchr_item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.ChecklistItem'),
        ),
        migrations.AlterUniqueTogether(
            name='processochecklistresposta',
            unique_together=set(),
        ),
    ]
