# Generated by Django 2.2.28 on 2026-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_auto_20260824_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='processochecklistresposta',
            name='proc_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
