# Generated by Django 2.2.28 on 2026-08-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_processochecklistresposta_proc_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processochecklistresposta',
            old_name='proc_desc',
            new_name='pchr_desc',
        ),
    ]
