# Generated by Django 2.2.28 on 2026-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0007_auto_20260824_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='proc_iter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processochecklistresposta',
            name='pchr_iter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
