# Generated by Django 2.2.28 on 2026-08-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_auto_20260825_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='proc_iter',
            new_name='proc_vers',
        ),
        migrations.RenameField(
            model_name='processochecklistresposta',
            old_name='pchr_iter',
            new_name='pchr_vers',
        ),
    ]
