# Generated by Django 2.2.28 on 2026-10-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0009_auto_20260825_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='proc_enti_assi',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
