# Generated by Django 2.2.28 on 2026-09-21 14:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEtiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa_id', models.CharField(max_length=50)),
                ('filial_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_papel', models.CharField(choices=[('A4', 'Folha A4'), ('BOBINA', 'Bobina')], default='A4', max_length=10)),
                ('orientacao', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=15)),
                ('largura_mm', models.DecimalField(decimal_places=2, default=40, max_digits=7)),
                ('altura_mm', models.DecimalField(decimal_places=2, default=60, max_digits=7)),
                ('colunas', models.PositiveSmallIntegerField(default=1)),
                ('linhas', models.PositiveSmallIntegerField(default=1)),
                ('margem_superior_mm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('margem_inferior_mm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('margem_esquerda_mm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('margem_direita_mm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('espacamento_horizontal_mm', models.DecimalField(decimal_places=2, default=2, max_digits=7)),
                ('espacamento_vertical_mm', models.DecimalField(decimal_places=2, default=2, max_digits=7)),
                ('configuracao', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('padrao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'produtos_modelo_etiqueta',
                'ordering': ['nome'],
            },
        ),
    ]
