from django.urls import include, path
from . import views
from Financeiro.Web.views import OrcamentoDashboardTemplateView

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("home/<slug:slug>/", views.home, name="home_slug"),
    path("home/<slug:slug>/<int:empresa>/<int:filial>/", views.home, name="home_slug_context"),
    path("<slug:slug>/home/", views.home_redirect_legacy, name="home_legacy"),
    path("home/selecionar-empresa/<int:empresa>/<int:filial>/", views.selecionar_empresa_redirect, name="selecionar_empresa_redirect"),
    path("home/<slug:slug>/selecionar-empresa/<int:empresa>/<int:filial>/", views.selecionar_empresa_redirect_slug, name="selecionar_empresa_redirect_slug"),

    # Páginas web
    path("login/", views.web_login, name="web_login"),
    path("selecionar-empresa/", views.selecionar_empresa, name="selecionar_empresa"),

    path("onboarding/complete/<str:step>/", views.complete_onboarding_step, name="onboarding_complete"),
    path("<slug:slug>/series/", include("series.Web.web_urls")),
    path("<slug:slug>/entidades/", include("Entidades.web_urls")),
    path("<slug:slug>/produtos/", include("Produtos.Web.web_urls")),
    path("<slug:slug>/formulacao/", include("formulacao.Web.web_urls")),
    path("<slug:slug>/pedidos/", include("Pedidos.Web.web_urls")),
    path("<slug:slug>/trocas-devolucoes/", include("TrocasDevolucoes.Web.web_urls")),
    path("<slug:slug>/orcamentos/", include("Orcamentos.Web.web_urls")),
    path("<slug:slug>/os/", include("O_S.Web.web_urls")),
    path("<slug:slug>/osexterna/", include("osexterna.Web.web_urls")),
    path("<slug:slug>/entradas/", include("Entradas_Estoque.Web.web_urls")),
    path("<slug:slug>/saidas/", include("Saidas_Estoque.Web.web_urls")),
    path("<slug:slug>/centrosdecustos/",include(("CentrodeCustos.web_urls", "centrosdecustos"), namespace="centrosdecustos"),
    ),
    # Financeiro
    path("<slug:slug>/contas-a-pagar/", include("contas_a_pagar.Web.web_urls")),
    path("<slug:slug>/contas-a-receber/", include("contas_a_receber.Web.web_urls")),
    path("<slug:slug>/lancamentos-bancarios/", include("Lancamentos_Bancarios.Web.web_urls")),
    path("<slug:slug>/orcamento/dashboard/", OrcamentoDashboardTemplateView.as_view(), name="orcamento_dashboard"),
    path("<slug:slug>/fluxo-de-caixa/", include("Financeiro.web_urls")),
    path("<slug:slug>/gerencial/", include("Gerencial.web_urls")),
    path("<slug:slug>/dre/", include("DRE.web_urls")),
    path("<slug:slug>/caixa-diario/", include("CaixaDiario.Web.web_urls")),
    path("<slug:slug>/licencas/", include("Licencas.web_urls")),
    path("<slug:slug>/onboarding/complete/<str:step>/", views.complete_onboarding_step, name="onboarding_complete_slug"),
    path("<slug:slug>/notas-destinadas/", include("NotasDestinadas.web_urls")),
    path("<slug:slug>/notas-fiscais/", include("Notas_Fiscais.Web.web_urls")),
    path("<slug:slug>/fiscal/", include("fiscal.web_urls")),
    path("<slug:slug>/cfop/", include("CFOP.Web.urls")),
    path("<slug:slug>/boletos/", include("boletos.Web.urls")),
    path("<slug:slug>/sped/", include("sped.Web.web_urls")),
    path("<slug:slug>/importador/", include("importador.urls")),
    path("<slug:slug>/notificacoes/", include("notificacoes.Web.web_urls")),
    path("<slug:slug>/coleta-estoque/", include("coletaestoque.Web.web_urls")),
    path("<slug:slug>/controle-de-ponto/", include("controledePonto.Web.web_urls")),
    path("<slug:slug>/controle-de-visitas/", include("controledevisitas.Web.web_urls")),
    path("<slug:slug>/agricola/", include("Agricola.Web.web_urls")),
    path("<slug:slug>/central-de-ajuda/", include("centraldeajuda.urls")),
    path("<slug:slug>/parametros-admin/", include("parametros_admin.web_urls")),
    path("<slug:slug>/perfil/", include("perfilweb.urls")),
    path("<slug:slug>/adiantamentos/", include("adiantamentos.Web.urls")),
    path("<slug:slug>/ordem-producao-joias/", include("OrdemProducao.Web.urls")),
    path("<slug:slug>/renegociacao/", include("Renegociacao.Web.web_urls")),
    path("<slug:slug>/bens/", include("bens.Web.urls")),
    path("<slug:slug>/transportes/", include("transportes.Web.urls")),
    path("<slug:slug>/auditoria/", include("auditoria.Web.urls")),
    path("<slug:slug>/gestao-obras/", include("GestaoObras.web.web_urls")),
    path("<slug:slug>/pisos/", include("Pisos.web.urls")),
    path("<slug:slug>/devolucoes-pisos/", include("devolucoes_pisos.Web.web_urls")),
    path("<slug:slug>/comissoes/", include("comissoes.Web.web_urls")),
    path("<slug:slug>/processos/", include("processos.urls")),
]
