# Generated by Django 2.2.28 on 2026-09-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicesrazao',
            fields=[
                ('indr_empr', models.IntegerField(primary_key=True, serialize=False)),
                ('indr_fili', models.IntegerField()),
                ('indr_lote', models.CharField(max_length=10)),
                ('indr_sequ', models.IntegerField()),
                ('indr_cont', models.IntegerField()),
                ('indr_cecu', models.IntegerField(blank=True, null=True)),
                ('indr_dbcr', models.CharField(blank=True, max_length=1, null=True)),
                ('indr_valo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('indr_data', models.DateField(blank=True, null=True)),
                ('indr_cont_part', models.IntegerField(blank=True, null=True)),
                ('indr_expa', models.CharField(blank=True, max_length=60, null=True)),
                ('indr_lanc_zera', models.BooleanField(blank=True, null=True)),
                ('indr_enti', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indicesrazao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planodecontas',
            fields=[
                ('plan_empr', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_redu', models.IntegerField()),
                ('plan_niv1', models.IntegerField(blank=True, null=True)),
                ('plan_expa', models.CharField(blank=True, max_length=60, null=True)),
                ('plan_grup', models.CharField(blank=True, max_length=60, null=True)),
                ('plan_nive', models.IntegerField(blank=True, null=True)),
                ('plan_anal', models.CharField(blank=True, max_length=1, null=True)),
                ('plan_natu', models.CharField(blank=True, max_length=2, null=True)),
                ('plan_refe', models.CharField(blank=True, max_length=60, null=True)),
                ('plan_dati', models.DateField(blank=True, null=True)),
                ('plan_data', models.DateField(blank=True, null=True)),
                ('plan_inat', models.BooleanField(blank=True, null=True)),
                ('plan_data_inat', models.DateField(blank=True, null=True)),
                ('plan_obse', models.TextField(blank=True, null=True)),
                ('plan_nome', models.CharField(blank=True, max_length=60, null=True)),
                ('plan_dre', models.CharField(blank=True, max_length=2, null=True)),
                ('plan_natu_sped', models.CharField(blank=True, max_length=2, null=True)),
                ('plan_flu1', models.CharField(blank=True, max_length=1, null=True)),
                ('plan_flu2', models.IntegerField(blank=True, null=True)),
                ('plan_de', models.IntegerField(blank=True, null=True)),
                ('plan_acer_comb', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planodecontas',
                'managed': False,
            },
        ),
    ]
