# Generated by Django 2.2.28 on 2026-09-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaTransp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocor_empr', models.IntegerField()),
                ('ocor_fili', models.IntegerField()),
                ('ocor_codi', models.TextField()),
                ('ocor_desc', models.TextField()),
                ('ocor_fina', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ocorrencia_transp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilOcorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfoc_empr', models.IntegerField()),
                ('pfoc_fili', models.IntegerField()),
                ('pfoc_desc', models.TextField()),
                ('pfoc_ativ', models.BooleanField(default=True)),
                ('ocorrencias', models.ManyToManyField(related_name='perfis', to='ocorrencias.OcorrenciaTransp')),
            ],
            options={
                'db_table': 'perfil_ocorrencia',
                'managed': True,
            },
        ),
    ]
