# Generated by Django 2.2.28 on 2026-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilocorrencia',
            name='ocorrencias',
            field=models.ManyToManyField(to='ocorrencias.OcorrenciaTransp'),
        ),
    ]
