# Generated by Django 2.2.28 on 2026-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportes", "0007_auto_20260506_0858"),
    ]

    operations = [
        migrations.AddField(
            model_name="regraibscbs",
            name="uf_origem",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="regraibscbs",
            name="uf_destino",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="regrapiscofins",
            name="uf_origem",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="regrapiscofins",
            name="uf_destino",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]

