# Generated by Django 2.2.28 on 2026-05-19 11:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoGerencialConta',
            fields=[
                ('gere_empr', models.IntegerField(primary_key=True, serialize=False)),
                ('gere_redu', models.IntegerField()),
                ('gere_niv1', models.IntegerField(blank=True, null=True)),
                ('gere_expa', models.CharField(blank=True, max_length=60, null=True)),
                ('gere_grup', models.CharField(blank=True, max_length=60, null=True)),
                ('gere_nive', models.IntegerField(blank=True, null=True)),
                ('gere_anal', models.CharField(blank=True, max_length=1, null=True)),
                ('gere_natu', models.CharField(blank=True, max_length=2, null=True)),
                ('gere_refe', models.CharField(blank=True, max_length=60, null=True)),
                ('gere_dati', models.DateField(blank=True, null=True)),
                ('gere_data', models.DateField(blank=True, null=True)),
                ('gere_inat', models.BooleanField(blank=True, null=True)),
                ('gere_data_inat', models.DateField(blank=True, null=True)),
                ('gere_obse', models.TextField(blank=True, null=True)),
                ('gere_nome', models.CharField(blank=True, max_length=60, null=True)),
                ('gere_dre', models.CharField(blank=True, max_length=2, null=True)),
                ('gere_natu_sped', models.CharField(blank=True, max_length=2, null=True)),
                ('gere_de', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planocontasgerencial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoGerencialMascara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gere_empr', models.IntegerField()),
                ('gere_nome', models.CharField(default='Plano Gerencial', max_length=60)),
                ('gere_nive', django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Níveis')),
                ('gere_ativ', models.BooleanField(default=True, verbose_name='Ativo')),
                ('gere_cria_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('gere_atual_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'db_table': 'plano_gerencial_mascara',
            },
        ),
        migrations.AddConstraint(
            model_name='planogerencialmascara',
            constraint=models.UniqueConstraint(condition=models.Q(gere_ativ=True), fields=('gere_empr',), name='unique_mascara_gerencial_ativa_por_empresa'),
        ),
    ]
